channels:
- conda-forge
- nodefaults  
dependencies:
- pandas
- requests
- autopep8
- pylint
- black
- isort
- mypy
- pip
- pytest
- pytest-cov
- make
- python-dotenv
- psycopg2
- pip:
    - apache-airflow
    - apache-airflow-providers-postgres
    - airflow-operators