channels:
- conda-forge
- nodefaults  
dependencies:
- pandas
- requests
- autopep8
- pylint
- black
- isort
- mypy
- pip
- pytest
- pytest-cov
- make
- python-dotenv
- apache-airflow
- psycopg2
- apache-airflow-providers-postgres